### ISSUE TITLE
extra/letsencrypt: use existing CSR/key?

### ISSUE THREAD

**Issue by JamesTheAwesomeDude** [hsleisink/hiawatha#32]
Right now, the `extra/letsencrypt` script suite has a whole lot of RSA hardcoded into it. There is (seemingly) no way to use it with a preexisting CSR and/or private key.

````
root@box:/etc/hiawatha/letsencrypt# openssl ecparam -name prime256v1 -genkey | openssl ec -out test.key
read EC key
writing EC key
root@box:/etc/hiawatha/letsencrypt# ./letsencrypt --help^C
root@box:/etc/hiawatha/letsencrypt# openssl req -new -sha256 -key test.key -nodes -out test.csr -outform pem
You are about to be asked to enter information that will be incorporated
into your certificate request.
What you are about to enter is what is called a Distinguished Name or a DN.
There are quite a few fields but you can leave some blank
For some fields there will be a default value,
If you enter '.', the field will be left blank.
-----
Country Name (2 letter code) [AU]:US
State or Province Name (full name) [Some-State]:.
Locality Name (eg, city) []:.
Organization Name (eg, company) [Internet Widgits Pty Ltd]:.
Organizational Unit Name (eg, section) []:TEST
Common Name (e.g. server FQDN or YOUR name) []:test.ishygddt.xyz
Email Address []:tls@ishygddt.xyz

Please enter the following 'extra' attributes
to be sent with your certificate request
A challenge password []:
An optional company name []:
root@box:/etc/hiawatha/letsencrypt# ./letsencrypt register
Registering account.
Account registered successfully.
root@box:/etc/hiawatha/letsencrypt# ./letsencrypt request test.ishygddt.xyz test.csr
Authorizing test.ishygddt.xyz.
 - Retrieving HTTP authentication challenge.
 - Retrieving authorization key.
Generating RSA key.
Generating CSR.
Retrieving certificate.
Writing private key and certificate to file.
Retrieving CA certificate.
Writing CA certificate to file.

root@box:/etc/hiawatha/letsencrypt#
````

As you can see, it seems to unconditionally generate both an `RSA key` and the CSR.

I really really like the minimalism of this self-contained client, especially when compared to certbot's sprawling system-integrated setup, but it would be nice if I could use it with ECDSA keys.

I don't actually care whether this would be done by hardcoding an option in for it, or just by permitting use of preexisting certificate requests (the latter one sounds both cleaner and easier to implement, IMO, but I am not a PHP developer, just a member of the peanut gallery 😜)

Thanks for the nice webserver, BTW.

**Comment by JamesTheAwesomeDude** [comment]
..although, this is less critical now that I just found [acme-tiny](https://github.com/diafygi/acme-tiny), which does support existing CSR with a "one-liner" (technically 3 but ehh)

````
openssl req -new\
 -outform pem\
 -out "${domain}.csr"\
 -newkey ec\
  -pkeyopt ec_paramgen_curve:secp384r1\
  -nodes\
  -keyout "${domain}.key"\
 -subj /C=US/O="Hacker, Inc."/OU="Web Server"/CN="${domain}"/subjectAltName="DNS.1=www.${domain}"\
 -keyform pem &&\
python acme_tiny.py\
 --account-key /etc/ssh/ssh_host_rsa_key\
 --acme-dir "/var/www/${domain}/.well-known/acme-challenge/"\
 --csr "${domain}.csr"\
 > "${domain}.crt" &&\
cat "${domain}.key" "${domain}.crt" > "${domain}.pem"
````

Is what I'm requesting just out-of-scope for this project, since it's covered by other projects..?

**Comment by hsleisink** [comment]
I'll take a look at support for ECC.

**Comment by hsleisink** [comment]
I've looked at it several times. I think the only sane option is to wait for PHP v7.2, which has ECC support. Otherwise, the only option is to drag in large amounts of libraries for ECC support, which is a no-go for me for maintenance reason.

**Comment by JamesTheAwesomeDude** [comment]
But I'm not asking about ECC specifically (although it does happen to be the current case)

I'm asking about using existing CSR files

**Comment by hsleisink** [comment]
I always want to make things as easy as possible to use. Making the script use an already existing CSR file, makes it complex. Specially when existing certificates needs to be renewed, automatically. It will very likely cause issues for several people. And of course, I will end up receiving all sorts of questions about it at the Hiawatha forum. So, also to protect my spare time, I keep things simple in order to simply make it work.
