### ISSUE TITLE
Debian update broke the server

### ISSUE THREAD

**Issue by marxenegls** [hsleisink/hiawatha#34]
This is a direct link to a deb package apparently 
http://mirror.tuxhelp.org/debian/
--only after running update i could no longer launch, access nor find hiawatha . I had it up and running with ssl both on localhost and fqdn, now it's all gone . I tried compiling it from src but had a few glitches .which reminds me why is the cmake installation referred to in the same terms and dir as that of hiawatha ? it's confusing to say the least. Install Cmake first ? which one you provided within the same directory ? 
It's a small webserver why is it made to look so unnecessarily complicated ? 
bon i'm gonna try to work backwards and start by removing that apt/sources.list.d/hiawatha entry

**Comment by hsleisink** [comment]
I don't know much about tuxhelp.org. Contact its maintainer in case of any issue.

I advice you to install cmake via apt-get and build a Hiawatha package via the script extra/make_debian_package.
