### ISSUE TITLE
reversproxy with specific domain not working

### ISSUE THREAD

**Issue by gfvh** [hsleisink/hiawatha#35]
Hi

I have really weird issue. Below domain does not get reversed. Shows hiawatha installed web page. Same OS with other web server os gets reverse proxied just fine. I do have several VirtualHost this way and all others with other names get reversed. I have made sure that backend has this host enabled at http server.

```
VirtualHost {
        Hostname = honestlyreview.com
        ReverseProxy .* http://127.0.0.1/ 30 keep-alive
        WebsiteRoot = /dev/null
        ExecuteCGI = no
        PreventXSS = yes
        PreventCSRF = yes
        PreventSQLi = yes
        CustomHeader = X-Frame-Options: DENY
        RandomHeader = 512
}

```
hiawatha -v
Hiawatha v10.7

**Comment by hsleisink** [comment]
When I request honestlyreview.com, it's redirected to www.honestlyreview.com. The www. is not in the Hostname list. Could that be the issue? So, like this:

```
VirtualHost {
	Hostname = honestlyreview.com, www.honestlyreview.com
	... 
```

**Comment by gfvh** [comment]
Hi

Didn't think of that. Now works

Thank you!
