### ISSUE TITLE
ShowIndex cannot show hidden files

### ISSUE THREAD

**Issue by ryu0** [hsleisink/hiawatha#37]
I recently was trying to configure Hiawatha to show directory listings but I noted that it doesn't show hidden files at all even if AllowDotFiles is enabled for the virtual host. I was looking through the source code and found out why this is. The C function, read_filelist, is hard-coded to ignore all hidden files. I think there should be a way to show hidden files if the system administrator wishes to do so. Would you be open to this kind of feature? I was thinking one option would be to extend AllowDotFiles to be able to control whether hidden files show up or not when ShowIndex is enabled. Thoughts?

**Comment by hsleisink** [comment]
Sounds like a good plan. I'll take a look at it.

**Comment by ryu0** [comment]
If you're not opposed, I already have an idea for how to modify the existing code. I'll try to get a pull request done soon.

**Comment by hsleisink** [comment]
Feature implemented. Available upon next release.
