### ISSUE TITLE
Certain filenames break directory listings

### ISSUE THREAD

**Issue by ryu0** [hsleisink/hiawatha#38]
While configuring Hiawatha to display directory listings for a folder, I discovered that some of the files broke the generation of the directory listing. I traced it back to how some of the files are named.

Steps to Reproduce:

1) Configure a directory to show a directory listing.
2) Place a file named index.html?view=tar&pathrev=813 in the directory.
3) Access the directory through a web browser.

Expected Results: A directory listing is shown in the web browser.
Actual Results: An empty web page is shown and an error appears in the error log file. The error was "
[omitted]|[omitted]|/var/www/hiawatha/distfiles/|data is invalid XML"

**Comment by hsleisink** [comment]
Holy crap, who came up with that filename? 😄 But, fair enough, it's a bug and I got it fixed for the next release. Probably somewhere soon after Let's Encrypt activates their ACME v2 API.
