### ISSUE TITLE
logging to syslog

### ISSUE THREAD

**Issue by mistepien** [hsleisink/hiawatha#39]
I would be great for hawiatha to be able to log to syslog instead of files.
This is important in case of embedded systems.

**Comment by hsleisink** [comment]
Log what exactly? Everything?

**Comment by mistepien** [comment]
exactly. busybox syslog can log to shared mem buffer (so no device is used) and to other syslog via port UDP:514.

**Comment by hsleisink** [comment]
Should this be a single setting for all log output or a per logfile setting? My guess is that when you want to log to syslog, you want to log all output to syslog. Right?

**Comment by mistepien** [comment]
in case of nginx logging to syslog is done together with logging to file.
error_log  syslog:server=unix:/dev/log;
access_log  syslog:server=unix:/dev/log;

in hiawatha.conf there is:
accesslogfile
errorlogfile
systemlogfile
garbagelogfile

In my opinion ypu should keep previous syntax (for sake of compatibility with older configurations)
and add new path, for instance one word: syslog. Just like in the mpd.conf (Music Player Daemon).

> 
log_file <file>
This specifies where the log file should be located.
The special value "syslog" makes MPD use the local syslog daemon.
