### ISSUE TITLE
cert not working when generated with certbot

### ISSUE THREAD

**Issue by commandline-be** [hsleisink/hiawatha#41]
Using Alpine Linux i could not get letsencrypt working as expected, so i switched to using certbot

After much trial and error i managed to generate/renew the certs but now i get 

```
 hiawatha -d
Error loading private key from tls/0000_cert.pem: PK - Invalid key tag or value (-0x3D00)
```

this was generated with certbot using

`certbot certonly --manual --csr domain-csr.txt --preferred-challenges dns-01`

**Comment by hsleisink** [comment]
In Hiawatha, the private key, the certificate en optionally the intermediate CA certificates all need to be in the same file ([url]https://www.hiawatha-webserver.org/howto/bindings[/url]). Seems the private key is missing in your certificate file.

What do you mean with 'I could not get letsencrypt working as expected'? What exactly went wrong?

**Comment by commandline-be** [comment]
Thanks Hugo, makes perfect sense with what I have seen. Cert bot produced three (cert + chain0 + chain1 )

I use hiawatha with Alpine Linux. Letsencrypt validates over http but I have no .well-known configured. With certbot I use  --preferred-challenges dns-01 to generate the certs.

**Comment by hsleisink** [comment]
Hiawatha's letsencrypt script creates (and removes afterwards) the .well-known directory for you. Or what letsencrypt script are you talking about? My advice is to use Hiawatha's letsencrypt script as it's tightly intergrated with how Hiawatha works.

Source at [url]https://github.com/hsleisink/hiawatha/tree/master/extra/letsencrypt[url]

**Comment by commandline-be** [comment]
I understand, maybe I misread the instructions but it did not work as expected. I will try again later today.

**Comment by commandline-be** [comment]
Hello Hugo,

Sorry to persist on this.  After a lot of do and redo and whatever i now have the certificates generated.

```
#ls 
README  cert.pem  chain.pem  fullchain.pem  privkey.pem
```

Still, no matter what certificate i try i get 

`hiawatha -d
Error loading private key from tls/webcertificate.crt: PK - Invalid key tag or value (-0x3D00)`

I've checked with ` openssl x509 -in fullchain.pem -text -noout` which shows the contents for the certificate nicely.

**Comment by hsleisink** [comment]
Does tls/webcertificate.crt contain a private key?

**Comment by commandline-be** [comment]
The Readme says

 cat README
This directory contains your keys and certificates.

`privkey.pem`  : the private key for your certificate.
`fullchain.pem`: the certificate file used in most server software.
`chain.pem`    : used for OCSP stapling in Nginx >=1.3.7.
`cert.pem`     : will break many server configurations, and should not be used
                 without reading further documentation (see link below).

**Comment by hsleisink** [comment]
That does not answer the question 'does tls/webcertificate.crt contain a private key?'

**Comment by commandline-be** [comment]
True; If i copy privkey.pem onto it, it does, if i do that it get 

` hiawatha -d
Error loading X.509 certificates from tls/webcertificate.crt: X509 - The CRT/CRL/CSR format is invalid, e.g. different type expected (-0x2180)`

**Comment by hsleisink** [comment]
The file tls/webcertificate.crt needs to contain a privacy key AND a certificate. Optionally, it can contain the required intermediate certificates.

**Comment by commandline-be** [comment]
Fixed; desperate measures etc, only this was left to make sense, and it works. The procedure being

```
cp privekey.pm /usr/local/etc/hiawatha/tls/webcertificate.crt
cat fullchain.pem >> /usr/local/etc/hiawatha/tls/webcertificate.crt
```

**Comment by DavidOliver** [comment]
@commandline-be, it seems that [certbot doesn't have the option to include the private key in a pem file](https://certbot.eff.org/docs/using.html#certbot-command-line-options). I'm sure the concatenation of the two files could be automated, but I can recommend Hugo's PHP script if your site(s) can be accessed via http (port 80); it's been working well for me for many months. I have it run via cron with sudo privileges so that the certificates belong to root and get put in the right place, and I only have to run the request command and touch the config when I'm adding a new site.

**Comment by Tianjiao** [comment]
@DavidOliver, Hi, just set the permission of the certificates to the User ID of the webserver so that they can be fetched. You could take a look at [here](https://en.wikipedia.org/wiki/Principle_of_least_privilege). Sudo privilege and root belonging is not usually done in automated script. However, it is too much for newbie like myself.

**Comment by DavidOliver** [comment]
@Tianjiao, thanks. If I remember correctly, there was something about running the Hiawatha Let's Encrypt script as root that triggered a certain desirable-to-me-at-the-time behaviour (moving to a particular directory?), but I'll take another look when I get a chance. :)

**Comment by commandline-be** [comment]
Thanks for the kind follow up. I chose to run Alpine Linux. For some reason or other the Hiawatha letsencrypt php scripts do not work as expected. I wrote down the procedure with cert bot and believe I am fine now. Though I do think letsencrypt is quite technically complete from an administrator point of view the wealth of clients and way of handling is rubbish.

**Comment by DavidOliver** [comment]
Hmm, I seem to remember finding certbot awkward, which is one reason I like Hugo's PHP script. There are other options, too, of course, and some of those look quite nice to use.

> For some reason or other the Hiawatha letsencrypt php scripts do not work as expected.

What happened?

**Comment by commandline-be** [comment]
I very much appreciate Hugo's efforts on both Hiawatha and the Letsencrypt script but on Alpine it just don't work. I will not look into it any further as I have a working procedure. I had the account.key and a domain-csr file. I have been messing with Letsencrypt agents for three evenings in a row.

No big fan of Letsencrypt to start with. I think I rather go out and buy a cert after this experience.

**Comment by Tianjiao** [comment]
@commandline-be , Hi, if you would have decided to buy a cert, my advice is that to ask the CA provider how to revoke the certificate, in case that your private key is thought to have been compromised. 

Let's Encrypt is famous for its automation, if you buy a cert, there would be a lot of manual work to do, so prepare for it.
