### ISSUE TITLE
Small ConnectionTotals setting causes crash with:  pthread create error: Resource temporarily unavailable

### ISSUE THREAD

**Issue by muhlemmer** [hsleisink/hiawatha#42]
When setting `ConnectionTotals` to a smaller value in `hiawatha.conf` , it causes Hiawatha to crash with:
````
pthread create error: Resource temporarily unavailable
````
I'm using Gentoo Linux x86_64, no-multilib, stable

This bug occurred on a single core VPS first, using Hiawatha 10.8.1. The limit on the single cored machine is at `ConnectionTotals = 22`. I've also tested this on a 4 core / 8 threads machine, the limit there is somewhere between 300 and 400.

Small note: the single core VPS is using a hardened profile, in case it matters.

The bug is also reproducible on version 9.15, at which I stopped testing.

## Steps to reproduce
1. Install Hiawatha 9.15 or 10.8.1, with a default `hiawatha.conf`
2. Set `ConnectionTotals = 20` in `hiawatha.conf`
3. Run `wigwam`
4. Run `hiawatha -d`

## Results
````shell
bld ~ # wigwam
Using /etc/hiawatha
Reading hiawatha.conf
No non-fatal errors found in the Hiawatha configuration.
bld ~ # hiawatha -d
Press Ctrl-C to shutdown the Hiawatha webserver.
pthread create error: Resource temporarily unavailable
Error initializing workers module.
````

## Expected results
One out of the following, by order of preference 
1. Don't crash, it seems it's just a matter of allocating less threads?
2. Wigwam reporting that the set value is too low
3. Hiawatha to crash with a more descriptive error, eg: `ConnectionTotals < whatever minimum`

I'm sorry, but my systems don't have frame pointers or debug handles compiled, so I won't be able to attach a trace unless I'm recompiling critical parts of the system. Hopefully this is reproducible on other systems.

Maybe related, although old and the OP never replied: https://www.hiawatha-webserver.org/forum/topic/1533

**Comment by muhlemmer** [comment]
Setting SetResourceLimits to 'no' indeed prevents this crash from happening, even with smaller values.

**Comment by hsleisink** [comment]
I'll take a look at this for the next release. Thanks.
